// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.ApiDbContext;

#nullable disable

namespace RestApiSample.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230412131711_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.User.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(550)
                        .HasColumnType("varchar(550)");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
